# Generated by Django 3.1.5 on 2021-05-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Task_name', models.CharField(max_length=25)),
                ('Task_desc', models.CharField(max_length=300)),
                ('timing', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
