# Generated by Django 3.1.5 on 2021-05-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('contact', models.IntegerField()),
                ('desc', models.CharField(max_length=250)),
            ],
        ),
    ]
