# Generated by Django 3.1.5 on 2021-05-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('contact', models.IntegerField()),
                ('desc', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
